"""Добавлено поле is_processed в ScanHistory

Revision ID: 7e6f35786884
Revises: a1b2897b2026
Create Date: 2025-03-14 17:31:47.422334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6f35786884'
down_revision = 'a1b2897b2026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_column('is_processed')

    # ### end Alembic commands ###
