"""Добавил is_global в Notification

Revision ID: 8890b7b2c158
Revises: e33be1c8b51b
Create Date: 2025-02-26 14:08:48.933782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8890b7b2c158'
down_revision = 'e33be1c8b51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###
