"""обавлено поле product_name в ScanHistory

Revision ID: a1b2897b2026
Revises: f4b2fcfcac1d
Create Date: 2025-03-13 17:53:13.581686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2897b2026'
down_revision = 'f4b2fcfcac1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('haram_ingredients', sa.Text(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('haram_ingredients')
        batch_op.drop_column('status')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('image')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
