"""обавлены статус и харамные ингредиенты в Product

Revision ID: f4b2fcfcac1d
Revises: 8890b7b2c158
Create Date: 2025-03-13 16:07:27.117403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b2fcfcac1d'
down_revision = '8890b7b2c158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('haram_ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('haram_ingredients')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
